version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: buildfiles/Dockerfile
    command:
      - "python"
      - "__main__.py"
    restart: always
    depends_on:
      - redis
      - db

  flowers:
    build:
      context: .
      dockerfile: buildfiles/Dockerfile
    command:
      - "python"
      - "main_flower.py"
    restart: always
    depends_on:
      - redis
      - db
    ports:
      - "8000:8000"

  redis:
    build:
      context: .
      dockerfile: buildfiles/RedisDockerfile
    restart: always
    ports:
      - "6379:6379"

  db:
    image: postgres:15-alpine
    env_file:
      - .env
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: on-failure
    ports:
      - "5432:5432"

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - flowers

volumes:
  pgdata:
